version: '3'

volumes:
  pgsql-db-data:
    driver: local
  pg-admin-data:
    driver: local


services:
    base: &base
        hostname: app
        image: weather-api
        stdin_open: true
        tty: true
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - .:/home/python/app
        environment: &env
            ENV: "development"
            LOG_LEVEL: "debug"
            PYTHONPATH: "/home/python/app"
            WEB_APP_DEBUG: "true"
            WEB_APP_DESCRIPTION: "weather Task Management Application"
            WEB_APP_TITLE: "weather"
            WEB_APP_VERSION: "0.0.1"
            WEB_SERVER_HOST: "0.0.0.0"
            WEB_SERVER_PORT: 8000
            WEB_SERVER_RELOAD: "true"

    app:
        <<: *base
        command: /bin/ash -c "poetry install && alembic upgrade head && uvicorn weather:web_app --host 0.0.0.0 --reload"
        ports:
          - "8000:8000"

    lint:
        <<: *base
        command: /bin/ash -c "poetry install && flake8 weather/ tests/"
        
    static-analysis:
        <<: *base
        command: /bin/ash -c "poetry install && mypy weather/ tests/"

    tests:
        <<: *base
        command: /bin/ash -c "poetry install && alembic upgrade head && pytest"
        environment:
          <<: *env
          ENV: "testing"
          DATABASE_PG_URL: "postgresql://postgres:dev1234@pgsql-db/weather_test"